# Generated by Django 4.2.3 on 2023-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_content_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
