# Generated by Django 4.2.6 on 2023-10-24 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pe'), ('accepted', 'Ac')], default='pending')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_student_course', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_student_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
